### ISSUE TITLE
Hue, Python, and psycopg2

### ISSUE THREAD

**Issue by razorsedge** [cloudera/director-scripts#46]
I am failing to understand why the `c6/hue-c6.sh` goes to all the effort to install compilers, `pip`, and dummy RPMs when a simpler solution is to deploy a pre-built python-psycopg2 RPM that meets Hue's requirements.

In fact, I am kind of appalled that [Cloudera's solution](https://www.cloudera.com/documentation/enterprise/6/6.0/topics/cm_ig_extrnl_pstgrs.html#id_inq_bgy_52b) to the overall problem of the OS shipping old versions of pyscopg2 is to install `pip` and build from source.

**Comment by bhavanki** [comment]
Hi razorsedge,

The script that we have posted is definitely only an "example" of what to do to work around the issue of the psycopg2 dependency. We found that it works, but there are certainly other ways to achieve the results that the script does, and you can definitely employ those instead. Anyone with a better solution can post a PR here and we can see about replacing what's there now.

IIRC, the installation of gcc isn't necessary to explicitly compile anything, but as a prerequisite for installing the psycopg2 package into the SCL Python distribution using pip. Does pip do compilation during the normal install procedure for psycopg2?

Hue itself uses the Python installation on its system, so it makes some sense to install psycopg2, which is a Python package, using pip. Research on our end didn't reveal an available RPM alternative that was new enough for Hue's new requirements.

The creation of a dummy RPM for psycopg2 2.5.1 is indeed weird, and its purpose is to turn the installation of that RPM into a no-op. The RPM is a dependency of the Cloudera Manager agent package. I agree it should be possible to create an RPM for a newer version of psycopg2. If done the right way, that would neuter the dependency on the older version, and probably remove the need to install the driver through pip. We decided, for a few reasons, that we shouldn't try to host such an RPM, but anyone can for their own uses. Again, what we have is just an example.

The psycopg2 RPM dependency that is the root of this problem is being looked at by the Cloudera Manager team, so hopefully, before too long, this entire workaround can be left behind.

**Comment by bhavanki** [comment]
This issue was resolved with the release of Cloudera Manager 6.1. See the Director release notes on the subject for details.

https://docs.cloudera.com/documentation/director/latest/topics/director_rn_known_issues.html#DIR-8665
